/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LicenseRegistry } from "./LicenseRegistry";
export * as factories from "./factories";
export { LicenseRegistry__factory } from "./factories/LicenseRegistry__factory";
