/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LicenseRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeOfficer"
      | "authorizedOfficers"
      | "deauthorizeOfficer"
      | "getVehicleLicenses"
      | "isLicenseValid"
      | "issueLicense"
      | "revokeLicense"
      | "rtsaAuthority"
      | "verifyLicense"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LicenseIssued"
      | "LicenseRevoked"
      | "OfficerAuthorized"
      | "OfficerDeauthorized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeOfficer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedOfficers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deauthorizeOfficer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVehicleLicenses",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isLicenseValid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueLicense",
    values: [
      string,
      BigNumberish,
      BytesLike,
      string,
      string,
      string,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeLicense",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rtsaAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyLicense",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeOfficer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedOfficers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deauthorizeOfficer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVehicleLicenses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isLicenseValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rtsaAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyLicense",
    data: BytesLike
  ): Result;
}

export namespace LicenseIssuedEvent {
  export type InputTuple = [
    licenseHash: BytesLike,
    vehicleNumber: string,
    year: BigNumberish,
    expiryDate: BigNumberish
  ];
  export type OutputTuple = [
    licenseHash: string,
    vehicleNumber: string,
    year: bigint,
    expiryDate: bigint
  ];
  export interface OutputObject {
    licenseHash: string;
    vehicleNumber: string;
    year: bigint;
    expiryDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LicenseRevokedEvent {
  export type InputTuple = [licenseHash: BytesLike, reason: string];
  export type OutputTuple = [licenseHash: string, reason: string];
  export interface OutputObject {
    licenseHash: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfficerAuthorizedEvent {
  export type InputTuple = [officer: AddressLike];
  export type OutputTuple = [officer: string];
  export interface OutputObject {
    officer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfficerDeauthorizedEvent {
  export type InputTuple = [officer: AddressLike];
  export type OutputTuple = [officer: string];
  export interface OutputObject {
    officer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LicenseRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LicenseRegistry;
  waitForDeployment(): Promise<this>;

  interface: LicenseRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeOfficer: TypedContractMethod<
    [officer: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedOfficers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  deauthorizeOfficer: TypedContractMethod<
    [officer: AddressLike],
    [void],
    "nonpayable"
  >;

  getVehicleLicenses: TypedContractMethod<
    [vehicleNumber: string],
    [string[]],
    "view"
  >;

  isLicenseValid: TypedContractMethod<
    [licenseHash: BytesLike],
    [boolean],
    "view"
  >;

  issueLicense: TypedContractMethod<
    [
      vehicleNumber: string,
      year: BigNumberish,
      licenseHash: BytesLike,
      roadTaxReference: string,
      insuranceReference: string,
      fitnessReference: string,
      validityDays: BigNumberish,
      metadata: string
    ],
    [void],
    "nonpayable"
  >;

  revokeLicense: TypedContractMethod<
    [licenseHash: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  rtsaAuthority: TypedContractMethod<[], [string], "view">;

  verifyLicense: TypedContractMethod<
    [licenseHash: BytesLike],
    [
      [string, bigint, boolean, boolean, boolean, bigint, bigint, string] & {
        vehicleNumber: string;
        year: bigint;
        isValid: boolean;
        isRevoked: boolean;
        isExpired: boolean;
        issuedTime: bigint;
        expiryDate: bigint;
        metadata: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeOfficer"
  ): TypedContractMethod<[officer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedOfficers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deauthorizeOfficer"
  ): TypedContractMethod<[officer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getVehicleLicenses"
  ): TypedContractMethod<[vehicleNumber: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "isLicenseValid"
  ): TypedContractMethod<[licenseHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issueLicense"
  ): TypedContractMethod<
    [
      vehicleNumber: string,
      year: BigNumberish,
      licenseHash: BytesLike,
      roadTaxReference: string,
      insuranceReference: string,
      fitnessReference: string,
      validityDays: BigNumberish,
      metadata: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeLicense"
  ): TypedContractMethod<
    [licenseHash: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rtsaAuthority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyLicense"
  ): TypedContractMethod<
    [licenseHash: BytesLike],
    [
      [string, bigint, boolean, boolean, boolean, bigint, bigint, string] & {
        vehicleNumber: string;
        year: bigint;
        isValid: boolean;
        isRevoked: boolean;
        isExpired: boolean;
        issuedTime: bigint;
        expiryDate: bigint;
        metadata: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "LicenseIssued"
  ): TypedContractEvent<
    LicenseIssuedEvent.InputTuple,
    LicenseIssuedEvent.OutputTuple,
    LicenseIssuedEvent.OutputObject
  >;
  getEvent(
    key: "LicenseRevoked"
  ): TypedContractEvent<
    LicenseRevokedEvent.InputTuple,
    LicenseRevokedEvent.OutputTuple,
    LicenseRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OfficerAuthorized"
  ): TypedContractEvent<
    OfficerAuthorizedEvent.InputTuple,
    OfficerAuthorizedEvent.OutputTuple,
    OfficerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OfficerDeauthorized"
  ): TypedContractEvent<
    OfficerDeauthorizedEvent.InputTuple,
    OfficerDeauthorizedEvent.OutputTuple,
    OfficerDeauthorizedEvent.OutputObject
  >;

  filters: {
    "LicenseIssued(bytes32,string,uint256,uint256)": TypedContractEvent<
      LicenseIssuedEvent.InputTuple,
      LicenseIssuedEvent.OutputTuple,
      LicenseIssuedEvent.OutputObject
    >;
    LicenseIssued: TypedContractEvent<
      LicenseIssuedEvent.InputTuple,
      LicenseIssuedEvent.OutputTuple,
      LicenseIssuedEvent.OutputObject
    >;

    "LicenseRevoked(bytes32,string)": TypedContractEvent<
      LicenseRevokedEvent.InputTuple,
      LicenseRevokedEvent.OutputTuple,
      LicenseRevokedEvent.OutputObject
    >;
    LicenseRevoked: TypedContractEvent<
      LicenseRevokedEvent.InputTuple,
      LicenseRevokedEvent.OutputTuple,
      LicenseRevokedEvent.OutputObject
    >;

    "OfficerAuthorized(address)": TypedContractEvent<
      OfficerAuthorizedEvent.InputTuple,
      OfficerAuthorizedEvent.OutputTuple,
      OfficerAuthorizedEvent.OutputObject
    >;
    OfficerAuthorized: TypedContractEvent<
      OfficerAuthorizedEvent.InputTuple,
      OfficerAuthorizedEvent.OutputTuple,
      OfficerAuthorizedEvent.OutputObject
    >;

    "OfficerDeauthorized(address)": TypedContractEvent<
      OfficerDeauthorizedEvent.InputTuple,
      OfficerDeauthorizedEvent.OutputTuple,
      OfficerDeauthorizedEvent.OutputObject
    >;
    OfficerDeauthorized: TypedContractEvent<
      OfficerDeauthorizedEvent.InputTuple,
      OfficerDeauthorizedEvent.OutputTuple,
      OfficerDeauthorizedEvent.OutputObject
    >;
  };
}
